# Generated by Django 5.0.7 on 2024-07-26 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0119_eventrule_event_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfield',
            name='related_object_filter',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
